app/api/models/trading.py
from flask_restx import Namespace, fields

api = Namespace('Trading Models')


sma_params = api.model('ParamsSMA', {
    'fast': fields.Integer(
        example=42,
        description='Fast moving average'),
    'slow': fields.Integer(
        example=252,
        description='Slow moving average')})


momentum_params = api.model('ParamsMomentum', {
    'period': fields.Integer(
        example=3,
        description='The number of rolling days to use as a signal.')})


mean_reversion_params = api.model('ParamsMeanReversion', {
    'sma': fields.Integer(
        example=28,
        description='Simple moving average.'),
    'threshold': fields.Float(
        example=3.0,
        description='Divergence from the mean threshold for signal.')})


ols_params = api.model('ParamsOLS', {
    'lags': fields.Integer(
        example=7,
        description='The number of lagged days to use for the signal.')})

app/models/stocks.py
from datetime import datetime, timedelta, date
import pandas_datareader as pdr
import yfinance as yf
import pandas as pd
from pandas import MultiIndex
from sqlalchemy import func
from .. import db
from ..utils import to_json_safe


STARTING_STOCKS = [
    ('AAPL', 'Apple, Inc.'),
    ('MSFT', 'Microsoft Corporation'),
    ('AMZN', 'Amazon.com, Inc.'),
    ('EURUSD=X', 'Euro / US Dollar Rate'),
    ('GDX', 'VanEck Gold Miners ETF'),
    ('GLD', 'SPDR Gold Trust'),
    ('META', 'Meta Platforms, Inc.'),
    ('CNA.L', 'Centrica plc'),
    ('SONY', 'Sony Group Coropration'),
    ('TTWO', 'Take-Two Interactive Software, Inc.'),
    ('NFLX', 'Netflix, Inc.'),
    ('SNOW', 'Snowflake Inc.'),
    ('VUAG.L', 'Vanguard S&P 500 ETF')
]


PORTFOLIO_STOCKS = ['META', 'CNA.L', 'AAPL', 'SONY', 'MSFT', 'TTWO', 'NFLXZ', 'SNOW', 'VUAG.L']


def get_stock_and_price_data(symbol, duration=None):
    duration = 10 if duration is None else int(duration)
    stock = Stock.query.filter_by(symbol=symbol).first_or_404()
    start_date = datetime.today() - pd.Timedelta(days=365 * duration)
    base_query = (StockPrice.query
                  .with_entities(StockPrice.date,
                                 StockPrice.adj_close)
                  .filter_by(symbol=symbol)
                  .filter(StockPrice.date >= start_date))
    prices = pd.read_sql(base_query.statement, base_query.session.bind)
    return stock, prices


class Stock(db.Model):
    __tablename__ = 'stocks'
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(64), unique=True)
    name = db.Column(db.String(64), unique=True)
    last_updated = db.Column(db.DateTime())

    @staticmethod
    def insert_stocks(stocks=STARTING_STOCKS):
        for symbol, name in stocks:
            stock = Stock.query.filter_by(symbol=symbol).first()
            if stock is None:
                stock = Stock(symbol=symbol, name=name, last_updated=None)
                db.session.add(stock)
                db.session.commit()

    def update(self):
        if self.last_updated is None or self.last_updated.date() < date.today():
            try:
                StockPrice.update(self.symbol)
                self.last_updated = datetime.now()
                db.session.add(self)
                db.session.commit()
            except Exception:
                # TODO - proper exception handling and logging here
                pass

    def to_dict(self, *exclude_keys):
        return {column.name: to_json_safe(getattr(self, column.name))
                for column in self.__table__.columns}

    def __repr__(self):
        return f"<Stock[{self.id}]: {self.name} ({self.symbol})>"


class StockPrice(db.Model):
    __tablename__ = 'stock_prices'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime())
    symbol = db.Column(db.String(10), db.ForeignKey('stocks.symbol'), index=True)
    open = db.Column(db.Float)
    close = db.Column(db.Float)
    adj_close = db.Column(db.Float)
    high = db.Column(db.Float)
    low = db.Column(db.Float)
    volume = db.Column(db.Integer)

    def __repr__(self):
        return f'<StockPrice[{self.id}]: {self.symbol} - {self.date.date()}>'

    @staticmethod
    def get_latest_date(symbol=None):
        latest_date = None
        if symbol is None:
            latest_dates = (StockPrice.query
                            .with_entities(StockPrice.symbol, func.max(StockPrice.date))
                            .group_by(StockPrice.symbol)
                            .all())
            if latest_dates:
                return min([x for _, x in latest_dates])
        else:
            latest_date = (StockPrice.query
                           .filter_by(symbol=symbol)
                           .with_entities(func.max(StockPrice.date))
                           .scalar())

        if latest_date is None:
            latest_date = (datetime.now() - timedelta(days=365*10)).date()

        return latest_date

    @staticmethod
    def get_price_data(symbols, start_date):
        if symbols is None:
            symbols = [x for x, *_ in Stock.query.with_entities(Stock.symbol).all()]
        try:
            data = pdr.yahoo.daily.YahooDailyReader(symbols=symbols, start=start_date).read()
        except TypeError:
            data = yf.download(tickers=symbols, start=start_date)
        return data

    @staticmethod
    def process_price_data(data, symbol=None):
        stock_prices = []
        if isinstance(data.columns, MultiIndex):
            if symbol is not None:
                raise ValueError("symbol value is not permitted when the price dataframe is MultiIndex.")
            symbols = data.columns.levels[1]
            for symbol in symbols:
                df = (data.xs(symbol, axis=1, level=1)
                          .dropna()
                          .reset_index()
                          .assign(symbol=symbol.upper())
                          .rename(columns=lambda x: x.replace(' ', '_').lower()))
                stock_prices.extend([StockPrice(**d) for d in df.to_dict(orient='records')])
        else:
            if symbol is None:
                raise ValueError("symbol must be supplied if the DataFrame contains price data for only a single stock.")
            df = (data.dropna()
                  .reset_index()
                  .assign(symbol=symbol.upper())
                  .rename(columns=lambda x: x.replace(' ', '_').lower()))
            stock_prices.extend([StockPrice(**d) for d in df.to_dict(orient='records')])
        return stock_prices

    @staticmethod
    def insert_stock_prices(stock_prices):
        db.session.add_all(stock_prices)
        db.session.commit()

    @staticmethod
    def update(symbol=None):
        start_date = StockPrice.get_latest_date(symbol) + timedelta(days=1)
        new_data = StockPrice.get_price_data(symbol, start_date)
        stock_prices = StockPrice.process_price_data(new_data, symbol=symbol)
        StockPrice.insert_stock_prices(stock_prices)

    def to_dict(self):
        return {column.name: to_json_safe(getattr(self, column.name))
                for column in self.__table__.columns}

app/trading/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, SelectField, FloatField
from wtforms.validators import DataRequired


class ParamsBase(FlaskForm):
    """Base parameters common to all trading strategies."""
    duration = SelectField('Trade duration (years)', choices=[5, 10], default=10, validators=[DataRequired()])
    submit = SubmitField('Calculate')


class ParamsSMA(ParamsBase):
    """Simple Moving Average trading strategy parameters."""
    fast = IntegerField('Fast Moving Average', default=42, validators=[DataRequired()])
    slow = IntegerField('Slow Moving Average', default=252, validators=[DataRequired()])

    def validate(self, extra_validators=None):
        super().validate(extra_validators=extra_validators)
        if self.fast.data >= self.slow.data:
            self.fast.errors.append('Fast moving average must be smaller than slow moving average')
            return False
        return True


class ParamsMomentum(ParamsBase):
    """Momentum trading strategy parameters"""
    period = IntegerField('Period', default=3, validators=[DataRequired()])


class ParamsMeanReversion(ParamsBase):
    """Mean Reversion trading strategy parameters."""
    sma = IntegerField('Simple Moving Average', default=28, validators=[DataRequired()])
    threshold = FloatField('Threshold', default=3.0, validators=[DataRequired()])


class ParamsOLS(ParamsBase):
    """OLS trading strategy parameters."""
    lags = IntegerField('Lags', default=7, validators=[DataRequired()])

app/trading/__init__.py
from flask import Blueprint
from .strategy import (
    SMA,
    MeanReversion,
    OLS,
    Momentum
)

trading = Blueprint('trading', __name__)

from . import views

app/trading/views.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required

from app.trading.strategy import SMA, OLS, MeanReversion, Momentum
from app.models.stocks import Stock, STARTING_STOCKS, PORTFOLIO_STOCKS, get_stock_and_price_data
from . import trading
from .forms import ParamsOLS, ParamsSMA, ParamsMomentum, ParamsMeanReversion


@trading.route('/stocks')
@login_required
def stocks():
    symbols = [x for x, _ in STARTING_STOCKS]
    stocks = Stock.query.filter(Stock.symbol.in_(symbols)).all()
    return render_template('trading/stocks.html', stocks=stocks, sample=False)


@trading.route('/sample-stocks')
def sample_stocks():
    symbols = [x for x in PORTFOLIO_STOCKS]
    stocks = Stock.query.filter(Stock.symbol.in_(symbols)).all()
    return render_template('trading/stocks.html', stocks=stocks, sample=True)


@trading.route('/trading-ideas')
def trading_ideas():
    return render_template('trading/trading_ideas.html')


@trading.route('/stocks/<symbol>')
def stock_page(symbol):
    stock = Stock.query.filter_by(symbol=symbol).first_or_404()
    stock.update()
    return render_template('trading/stock_page.html', stock=stock)


@trading.route('/stocks/<symbol>/simple-moving-average', methods=['GET', 'POST'])
def strategy_sma(symbol):
    form = ParamsSMA()
    fast = 42
    slow = 252
    duration = '10'

    if request.method == 'POST':
        if form.validate_on_submit():
            fast = form.fast.data
            slow = form.slow.data
            duration = form.duration.data
        else:
            flash('invalid input')
            redirect(url_for('trading.strategy_sma', symbol=symbol))

    stock, prices = get_stock_and_price_data(symbol, duration)
    stock.update()
    sma = SMA(prices, short_pos=-1)
    sma.fit(fast=fast, slow=slow)
    returns = sma.get_returns().to_dict()
    returns_script, returns_div = sma.get_returns_plot_components(stock)
    sma_script, sma_div = sma.get_sma_plot_components(stock)
    return render_template(
        'trading/strategy_sma.html',
        returns_script=returns_script,
        returns_div=returns_div,
        stock=stock,
        form=form,
        sma=sma,
        returns=returns,
        sma_script=sma_script,
        sma_div=sma_div,
        strategy='SMA')


@trading.route('/stocks/<symbol>/momentum', methods=['GET', 'POST'])
def strategy_momentum(symbol):
    form = ParamsMomentum()
    period = 3
    duration = '10'

    if request.method == 'POST':
        if form.validate_on_submit():
            period = form.period.data
            duration = form.duration.data
        else:
            redirect(url_for('trading.strategy_momentum', symbol=symbol))

    stock, prices = get_stock_and_price_data(symbol, duration)
    stock.update()
    momentum = Momentum(prices, short_pos=-1)
    momentum.fit(period=period)
    returns = momentum.get_returns().to_dict()
    returns_script, returns_div = momentum.get_returns_plot_components(stock)
    return render_template(
        'trading/strategy_momentum.html',
        returns_script=returns_script,
        returns_div=returns_div,
        stock=stock,
        form=form,
        momentum=momentum,
        returns=returns,
        strategy='Momentum')


@trading.route('/stocks/<symbol>/mean-reversion', methods=['GET', 'POST'])
def strategy_mean_reversion(symbol):
    form = ParamsMeanReversion()
    sma = 28
    threshold = 3.0
    duration = '10'

    if request.method == 'POST':
        if form.validate_on_submit():
            sma = form.sma.data
            threshold = form.threshold.data
            duration = form.duration.data
        else:
            redirect(url_for('trading.strategy_mean_reversion', symbol=symbol))

    stock, prices = get_stock_and_price_data(symbol, duration)
    stock.update()
    mean_rev = MeanReversion(prices, short_pos=-1)
    mean_rev.fit(sma=sma, threshold=threshold)
    returns = mean_rev.get_returns().to_dict()
    returns_script, returns_div = mean_rev.get_returns_plot_components(stock)
    distance_script, distance_div = mean_rev.get_distance_plot_components(stock)
    return render_template(
        'trading/strategy_mean_reversion.html',
        returns_script=returns_script,
        returns_div=returns_div,
        stock=stock,
        form=form,
        mean_rev=mean_rev,
        returns=returns,
        distance_script=distance_script,
        distance_div=distance_div,
        strategy='Mean-Reversion')


@trading.route('/stocks/<symbol>/ols', methods=['GET', 'POST'])
def strategy_ols(symbol):
    form = ParamsOLS()
    lags = 7
    duration = '10'

    if request.method == 'POST':
        if form.validate_on_submit():
            lags = form.lags.data
            duration = form.duration.data
        else:
            redirect(url_for('trading.strategy_ols', symbol=symbol))

    stock, prices = get_stock_and_price_data(symbol, duration)
    stock.update()
    ols = OLS(prices, short_pos=-1)
    ols.fit(lags=lags)
    returns = ols.get_returns().to_dict()
    returns_script, returns_div = ols.get_returns_plot_components(stock)
    return render_template(
        'trading/strategy_ols.html',
        returns_script=returns_script,
        returns_div=returns_div,
        stock=stock,
        form=form,
        ols=ols,
        returns=returns,
        strategy='OLS')

app/templates/trading/stock_page.html
{% extends "base/base.html" %}

{% block title %}Cadams - {{ stock.symbol }}{% endblock title %}

{% block content %}
{{ super() }}
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
            {% if current_user.is_authenticated %}
            <li class="breadcrumb-item"><a href="{{ url_for('trading.stocks') }}">Stocks</a></li>
            {% else %}
            <li class="breadcrumb-item"><a href="{{ url_for('trading.sample_stocks') }}">Stocks</a></li>  
            {% endif %}
          <li class="breadcrumb-item active" aria-current="page">{{ stock.symbol }}</li>
        </ol>
    </nav>

    <h1>{{ stock.name }} ({{ stock.symbol.upper() }}) Trading Stategies</h1>

    <p>Select a trading strategy</p>

    <div class="list-group">
      <a href="{{ url_for('trading.strategy_sma', symbol=stock.symbol) }}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Simple Moving Averages (SMA)</h5>
        </div>
        <!-- <p class="mb-1">Some placeholder content in a paragraph.</p> -->
      </a>
      <a href="{{ url_for('trading.strategy_momentum', symbol=stock.symbol) }}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Momentum</h5>
        </div>
        <!-- <p class="mb-1">Some placeholder content in a paragraph.</p> -->
      </a>
      <a href="{{ url_for('trading.strategy_mean_reversion', symbol=stock.symbol) }}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Mean Reversion</h5>
        </div>
        <!-- <p class="mb-1">Some placeholder content in a paragraph.</p> -->
      </a>
      <a href="{{ url_for('trading.strategy_ols', symbol=stock.symbol) }}" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Ordinary Least Squares (OLS)</h5>
        </div>
        <!-- <p class="mb-1">Some placeholder content in a paragraph.</p> -->
      </a>
      <a href="#" class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Deep Learning</h5>
        </div>
        <!-- <p class="mb-1">Some placeholder content in a paragraph.</p> -->
        <small>coming soon</small>
      </a>

    </div>


</div>
{% endblock content %}

app/templates/trading/stock_plot.html
{% extends "base/base.html" %}

{% block title %}Cadams - {{ stock.symbol }} - {{ strategy }}{% endblock title %}

{% block styles %}
{{ super() }}
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh.min.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh-widgets.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh-tables.css"
    rel="stylesheet" type="text/css">    
{% endblock styles %}

{% block content %}
{{ super() }}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('trading.stocks') }}">Stocks</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('trading.stock_page', symbol=stock.symbol) }}">{{stock.symbol}}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ strategy }}</li>
    </ol>
  </nav>

  <h1>{{strategy.title()}} Strategy For {{ stock.symbol.upper() }}</h1>

  <div class="container my-5">
    {{ div|safe }}
    {{ script|safe }}
  </div>

</div>
{% endblock content %}

{% block scripts %}
{{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh-widgets.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.4.3/bokeh-tables.js"></script>
{% endblock %}

app/templates/trading/stocks.html
{% extends "base/base.html" %}

{% block title %}Cadams - {% if sample %}
  Sample Stocks
{% else %}
  Stocks
{% endif %}{% endblock %}

{% block content %}
{{ super() }}
<div class="container">
    <div>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Stocks</li>
            </ol>
          </nav>
    </div>
    <div>
        <h1>
            Stocks
        </h1>
        {% if sample %}
        <p class="lead">
          These are some sample stocks that you can use to experiment with backtesting of various trading strategies.
        </p>
        <p>
          Create an account to select your own stocks to test.
        </p>
        {% endif %}
    </div>
    <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Symbol</th>
            <th scope="col">Name</th>
            <th scope="col">Charts</th>
          </tr>
        </thead>
        <tbody>
            {% for stock in stocks %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.name }}</td>
                <td>
                  <a class="btn btn-primary btn-sm" href="{{ url_for('trading.stock_page', symbol=stock.symbol) }}" role="button">Go</a>
                </td>
            </tr>
           {% endfor %}
        </tbody>
      </table>    
</div>
{% endblock %}

app/templates/trading/strategy_base.html
{% extends "base/base.html" %}

{% block title %}Cadams - {{ stock.symbol }}{% endblock title%}

{% block styles %}
{{ super() }}
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh.min.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh-widgets.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh-tables.css"
    rel="stylesheet" type="text/css">    
{% endblock styles %}

{% block content %}
{{ super() }}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
        {% if current_user.is_authenticated %}
        <li class="breadcrumb-item"><a href="{{ url_for('trading.stocks') }}">Stocks</a></li>
        {% else %}
        <li class="breadcrumb-item"><a href="{{ url_for('trading.sample_stocks') }}">Stocks</a></li>  
        {% endif %}
      <li class="breadcrumb-item"><a href="{{ url_for('trading.stock_page', symbol=stock.symbol) }}">{{stock.symbol}}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{strategy}}</li>
    </ol>
  </nav>

  {% block h1 %} {% endblock h1 %}
  {% block strategy_definition %} {% endblock strategy_definition %}

  <div class="container">
    <h5>Parameters</h5>

    <form method="POST">
        {{ form.hidden_tag() }}

    {% block custom_params %} {% endblock custom_params %}

    <div class="row mb-3 align-items-left">
      <div class="col-sm-2">
        {{ form.duration.label(class="col-form-label") }}
        <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Duration" data-bs-content="The number of years to hold or trade the financial instrument."></i>
      </div>
      <div class="col-auto">
        {{ form.duration(class="form-control") }}
      </div>
    </div>

    {{ form.submit(class="btn btn-primary") }}
    </form>
  </div>

  <div class="container my-5">
    <h2>Estimated Returns</h2>
    {{ returns_div|safe }}
    {{ returns_script|safe }}
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Kind</th>
        <th scope="col">Returns</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>Bought and held</td>
            <td>{{ "%.2f"|format(returns.returns) }}</td>
        </tr>
        <tr>
          <td>Traded with strategy</td>
          <td>{{ "%.2f"|format(returns.strategy) }}</td>
      </tr>
      </tbody>
  </table>
  
  {% block custom_plots %} {% endblock custom_plots %}
  
</div>



{% endblock content %}

{% block scripts %}
{{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh-widgets.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.5.0/bokeh-tables.js"></script>
    <script src="{{ url_for('static', filename='custom.js') }}"></script>
{% endblock %}

app/templates/trading/strategy_mean_reversion.html
{% extends "trading/strategy_base.html" %}

{% block title %}{{ super() }} - Simple Moving Average{% endblock title %}

{% block h1 %}
<h1>Mean Reversion Strategy For {{ stock.symbol.upper() }}</h1>
{% endblock h1 %}

{% block strategy_definition %}
<p></p>
{% endblock strategy_definition %}

{% block custom_params %}
  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.sma.label(class="col-form-label") }}
      <!-- <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Fast MA" data-bs-content="The moving average over a short period."></i> -->
    </div>
    <div class="col-auto">
      {{ form.sma(class="form-control") }}
    </div>
  </div>

  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.threshold.label(class="col-form-label") }}
      <!-- <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Slow MA" data-bs-content="The moving average over a long period."></i> -->
    </div>
    <div class="col-auto">
      {{ form.threshold(class="form-control") }}
    </div>
  </div>
{% endblock custom_params %}

{% block custom_plots %}
<div class="container my-5">
  <h2>{{ stock.name }} Price Distance From Mean</h2>
  {{ distance_div|safe }}
  {{ distance_script|safe }}
</div>
{% endblock custom_plots %}

app/templates/trading/strategy_momentum.html
{% extends "trading/strategy_base.html" %}

{% block title %}{{ super() }} - Simple Moving Average{% endblock title %}

{% block h1 %}
<h1>Momentum Strategy For {{ stock.symbol.upper() }}</h1>
{% endblock h1 %}

{% block strategy_definition %}
<p></p>
{% endblock strategy_definition %}

{% block custom_params %}
  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.period.label(class="col-form-label") }}
      <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Period" data-bs-content="The number of rolling days to use for the signal."></i>
    </div>
    <div class="col-auto">
      {{ form.period(class="form-control") }}
    </div>
  </div>
{% endblock custom_params %}

app/templates/trading/strategy_ols.html
{% extends "trading/strategy_base.html" %}

{% block title %}{{ super() }} - Ordinary Least Squares{% endblock title %}

{% block h1 %}
<h1>Ordinary Least Squares (OLS) Strategy For {{ stock.symbol.upper() }}</h1>
{% endblock h1 %}

{% block strategy_definition %}
<p></p>
{% endblock strategy_definition %}

{% block custom_params %}
  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.lags.label(class="col-form-label") }}
      <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Period" data-bs-content="The number of lagged days to use for the signal."></i>
    </div>
    <div class="col-auto">
      {{ form.lags(class="form-control") }}
    </div>
  </div>
{% endblock custom_params %}

app/templates/trading/strategy_sma.html
{% extends "trading/strategy_base.html" %}

{% block title %}{{ super() }} - Simple Moving Average{% endblock title %}

{% block h1 %}
<h1>Simple Moving Average Strategy For {{ stock.symbol.upper() }}</h1>
{% endblock h1 %}

{% block strategy_definition %}
<p></p>
{% endblock strategy_definition %}

{% block custom_params %}
  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.fast.label(class="col-form-label") }}
      <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Fast MA" data-bs-content="The moving average over a short period."></i>
    </div>
    <div class="col-auto">
      {{ form.fast(class="form-control") }}
    </div>
  </div>

  <div class="row mb-3 align-items-center">
    <div class="col-sm-2">
      {{ form.slow.label(class="col-form-label") }}
      <i tabindex="0" class="fa-regular fa-circle-question" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Slow MA" data-bs-content="The moving average over a long period."></i>
    </div>
    <div class="col-auto">
      {{ form.slow(class="form-control") }}
    </div>
    <div class="col-auto">
      <span id="fastHelp" class="form-text">
        Must be greater than fast moving average.
      </span>
    </div>
  </div>
{% endblock custom_params %}

{% block custom_plots %}
<div class="container my-5">
  <h2>{{ stock.name }} Price and Moving Averages</h2>
  {{ sma_div|safe }}
  {{ sma_script|safe }}
</div>
{% endblock custom_plots %}